/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuestionBanksRouteImport } from './routes/question-banks'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AnswersRouteImport } from './routes/answers'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBanksRoute = QuestionBanksRouteImport.update({
  id: '/question-banks',
  path: '/question-banks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersRoute = AnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answers': typeof AnswersRoute
  '/benchmarks': typeof BenchmarksRoute
  '/books': typeof BooksRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/question-banks': typeof QuestionBanksRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answers': typeof AnswersRoute
  '/benchmarks': typeof BenchmarksRoute
  '/books': typeof BooksRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/question-banks': typeof QuestionBanksRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answers': typeof AnswersRoute
  '/benchmarks': typeof BenchmarksRoute
  '/books': typeof BooksRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/question-banks': typeof QuestionBanksRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/answers'
    | '/benchmarks'
    | '/books'
    | '/history'
    | '/logs'
    | '/pipeline'
    | '/projects'
    | '/question-banks'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/answers'
    | '/benchmarks'
    | '/books'
    | '/history'
    | '/logs'
    | '/pipeline'
    | '/projects'
    | '/question-banks'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/answers'
    | '/benchmarks'
    | '/books'
    | '/history'
    | '/logs'
    | '/pipeline'
    | '/projects'
    | '/question-banks'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswersRoute: typeof AnswersRoute
  BenchmarksRoute: typeof BenchmarksRoute
  BooksRoute: typeof BooksRoute
  HistoryRoute: typeof HistoryRoute
  LogsRoute: typeof LogsRoute
  PipelineRoute: typeof PipelineRoute
  ProjectsRoute: typeof ProjectsRoute
  QuestionBanksRoute: typeof QuestionBanksRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-banks': {
      id: '/question-banks'
      path: '/question-banks'
      fullPath: '/question-banks'
      preLoaderRoute: typeof QuestionBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers': {
      id: '/answers'
      path: '/answers'
      fullPath: '/answers'
      preLoaderRoute: typeof AnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswersRoute: AnswersRoute,
  BenchmarksRoute: BenchmarksRoute,
  BooksRoute: BooksRoute,
  HistoryRoute: HistoryRoute,
  LogsRoute: LogsRoute,
  PipelineRoute: PipelineRoute,
  ProjectsRoute: ProjectsRoute,
  QuestionBanksRoute: QuestionBanksRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
